### ISSUE TITLE
Unable to load settings panel

### ISSUE THREAD

**Issue by Hamz-a** [nccgroup/HTTPSignatures#1]
When installing the plugin, a new *HTTP Signatures* menu item is created. However when clicking on it, nothing happens...

**Comment by sanktjodel** [comment]
Your recommended use of `menuButton.addMenuListener(this)` has the drawback that the menu opens accidentally by just moving the mouse over the HTTP Signatures menu and I therefore switched to using `addMouseListener`.

Can you please provide some more information about your system such as Burp version, free or pro, Java version, and OS.

Did you try to unload and load the extension?

**Comment by Hamz-a** [comment]
@sanktjodel I've seen other burp plugins use `menuButton.addMenuListener(this)` and I didn't experience accidental menu opening. The system I tested this on is MacOS Mojave using Burp Suite Pro v2021.2.1. I've also tried older versions of Burp Pro (late 2020), same problem. I did (un)load the extension several times.
